TestTaskBuyerForm/Controllers/BuyerFormController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Repository.Models.Domain;
using Repository.Data;
using Microsoft.EntityFrameworkCore;
using Repository.Interfaces;
using Service.Interfaces;
using Service.Services;

namespace TestTaskBuyerForm.Controllers
{
    public class BuyerFormController : Controller
    {
        private readonly IBuyerFormService _buyerFormService;

        public BuyerFormController(IBuyerFormService buyerFormService)
        {
            _buyerFormService = buyerFormService;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(BuyerForm buyerForm)
        {
            if (ModelState.IsValid)
            {
                await _buyerFormService.AddBuyerFormAsync(buyerForm);
                return RedirectToAction("Show");
            }
            return View(buyerForm);
        }

        [HttpGet]
        public async Task<IActionResult> Show(BuyerForm buyerForm)
        {
            var buyerFormList = await _buyerFormService.GetAllBuyerFormsAsync();
            return View(buyerFormList);
        }
    }
}

TestTaskBuyerForm/Views/BuyerForm/Create.cshtml
@model Repository.Models.Domain.BuyerForm

<h2>Add buyer</h2>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName"></label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Phone"></label>
        <input asp-for="Phone" class="form-control" />
        <span asp-validation-for="Phone" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>

TestTaskBuyerForm/Views/BuyerForm/Show.cshtml
@model IEnumerable<Repository.Models.Domain.BuyerForm>

<h2>Buyer list</h2>

<table class="table">
    <thead>
        <tr>
            <th>Ім'я</th>
            <th>Прізвище</th>
            <th>Електронна пошта</th>
            <th>Телефон</th>
            <th>Адреса</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var customer in Model)
        {
            <tr>
                <td>@customer.FirstName</td>
                <td>@customer.LastName</td>
                <td>@customer.Email</td>
                <td>@customer.Phone</td>
                <td>@customer.Address</td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-primary" asp-action="Create">Add buyer</a>

TestTaskBuyerForm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestTaskBuyerForm</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="BuyerForm" asp-action="Show">TestTaskBuyerForm</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BuyerForm" asp-action="Create">Create</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BuyerForm" asp-action="Show">Show</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>